### ISSUE TITLE
有办法调整清晰度么？

### ISSUE THREAD

**Issue by regou** [wean/PersimmonCakes#4]
用了感觉还不错，但是貌似不能调整清晰度啊？

**Comment by wean** [comment]
正准备在页面上添加些按钮，按照flvcd的说明，是可以支持清晰度调整，下个礼拜出差回来了弄了，谢谢支持 ^-^

**Comment by wean** [comment]
以及添加了清晰度解析了，先凑合着用youku吧，youku上先弄得比较好一点才行，重新调整了一下代码，可能会有点调整不到位引起的问题，再看吧。嘿，默认youku是超清的。
